### ISSUE TITLE
七牛云文件上传

### ISSUE THREAD

**Issue by haonanaJava** [lfb/nodejs-koa-blog#164]
我看你项目里有用七牛云对象存储，你把你的SECRET_KET暴露出来不会出问题吗

**Comment by hedongshu** [comment]
我已经用上了他的七牛云存了几张图片，感觉有点离谱，不太安全

**Comment by lfb** [comment]
> 我看你项目里有用七牛云对象存储，你把你的SECRET_KET暴露出来不会出问题吗

谢谢你哦
