### ISSUE TITLE
管理端编辑评论、回复时，显示 404

### ISSUE THREAD

**Issue by Shimada666** [lfb/nodejs-koa-blog#171]
![image](https://user-images.githubusercontent.com/33391300/147383034-401b603e-541c-4036-a6d5-eb861fd57c72.png)

![image](https://user-images.githubusercontent.com/33391300/147383029-4d53a91d-fce0-4bf3-b730-5e8c45b65213.png)

查看路由发现没有 /comment/edit 这条路由，请问该怎么办呢

**Comment by lfb** [comment]
> ![image](https://user-images.githubusercontent.com/33391300/147383034-401b603e-541c-4036-a6d5-eb861fd57c72.png)
> 
> ![image](https://user-images.githubusercontent.com/33391300/147383029-4d53a91d-fce0-4bf3-b730-5e8c45b65213.png)
> 
> 查看路由发现没有 /comment/edit 这条路由，请问该怎么办呢

谢谢你，我已修复了：）
