### ISSUE TITLE
大佬，全局对象global是怎么引入的？config/config.js文件 

### ISSUE THREAD

**Issue by MrZhongLC** [lfb/nodejs-koa-blog#178]

**Comment by lfb** [comment]
> _No description provided._

global对象，是node中的全局变量，类似浏览器中的window对象。global对象也有一个global属性引用自身。

module,exports,require,__dirname,__filename虽然可以全局访问，但他们并不属于global的属性，他们是每个模块引入时，包裹的匿名函数中的参数。

global对象的属性，是全局属性，在node中都可以直接访问。
