### ISSUE TITLE
服务器异常 code 应该是 500 吧？

### ISSUE THREAD

**Issue by Ha0ran2001** [lfb/nodejs-koa-blog#190]
![image](https://user-images.githubusercontent.com/73927445/159041120-6ea1cee7-0bf1-4ada-8dac-2ea4a881481a.png)

**Comment by lfb** [comment]
> ![image](https://user-images.githubusercontent.com/73927445/159041120-6ea1cee7-0bf1-4ada-8dac-2ea4a881481a.png)

是的，非常感谢
